### ISSUE TITLE
TypeError: Cannot set property 'invalid' of null

### ISSUE THREAD

**Issue by jarrodek** [cheonhyangzhang/paper-tags-input#7]
I receive following error:

> Uncaught TypeError: Cannot set property 'invalid' of null, paper-tags-input.html:262

It should not use following syntax:
`var input = document.querySelector('#tag-input');`
since it use shadow DOM.

If you replace it with:
`var input = Polymer.dom(this.root).querySelector('#tag-input');` 
it will be working.

**Comment by cheonhyangzhang** [comment]
Do you know how to reproduce this error? 
Like in what Browser and its version, 
example use of paper-tags-input and on what condition and events, you will receive the error.

**Comment by jarrodek** [comment]
It's about Polymer setup, not the browser. Your code will work if Polymer use [shady dom](https://www.polymer-project.org/1.0/articles/shadydom.html). However if you force to use shadow DOM this code will not work since elements will be encapsulated. 
Try change your code to use [shadow dom](http://www.html5rocks.com/en/tutorials/webcomponents/shadowdom/). [Put following script after webcomponents.js](https://www.polymer-project.org/1.0/docs/devguide/settings.html):

``` javascript
<script type="text/javascript">
    window.Polymer = window.Polymer || {};
    window.Polymer.dom = 'shadow';
</script>
```

This should cause the error.

**Comment by cheonhyangzhang** [comment]
Okay. Got you.  

I am still learning the whole Polymer thing and wondering what is the use case to use shadow dom instead of shady dom?

I know that in the version of 0.x, it is using shadow dom and then when the 1.0 version came out, they started to use shady dom.

**Comment by jarrodek** [comment]
Eventually they will switch on using shadow DOM by default. It's just a matter of time.

To see you work written more in Polymer way check my fork of your repository. I altered it couple of days ago.

**Comment by cheonhyangzhang** [comment]
The changes are made in v1.2.2, using Polymer DOM API in order to support the element to work correctly both in shady dom and shadow dom.
