### ISSUE TITLE
Adding tag to one instance adds it to all elements

### ISSUE THREAD

**Issue by bipin-nag** [cheonhyangzhang/paper-tags-input#8]
In the demo if you enter a new tag it is added  to all elements of paper-tags-input.

**Comment by cheonhyangzhang** [comment]
Yep. This is the expected behavior because for demonstrate purpose, all paper-tag-inputs are binding to the same variable.

**Comment by bipin-nag** [comment]
Can you give a small example where inputs work independently. I cannot make it work. Thanks.

**Comment by cheonhyangzhang** [comment]
In the demo, there is example for inputs works independently. For the last example, unicode example, it has its own data binded to paper-tags-inpu.
